apiVersion: apps/v1
kind: Deployment
metadata:
  name: hangman-game
spec:
  selector:
    matchLabels:
      app: hangman-game
  template:
    metadata:
      labels:
        app: hangman-game
    spec:
      containers:
      - name: hangman-game
        image: nicolasmartinss/hangman:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: hangman-game
spec:
  selector:
    app: hangman-game
  type: NodePort  
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000

